#+TITLE: Road Surface Disparity Estimation
AUTHORS: Anton Goretsky, Daniel Mallia, and Josh Winton

This project was created as a final project for the Computer Vision course at Hunter College in Spring 2020.

The algorithms used are based largely on those presented in these papers:
1. [[https://www.eurasip.org/Proceedings/Eusipco/Eusipco2013/papers/1569743475.pdf][Efficient Disparity Calculation Based on Stereo Vision With Ground Obstacle Assumption (Zhang et al., 2013)]]
2. [[https://www.researchgate.net/publication/322589687_Real-time_implementation_of_stereo_vision_based_on_optimised_normalised_cross-correlation_and_propagated_search_range_on_a_GPU][Real-Time Implementation of Stereo Vision Based on Optimised Normalized Cross-Correlation and Propagated Search Range on a GPU (Fan & Dahnoun, 2017)]]
3. [[https://arxiv.org/abs/1807.01874][Road Surface 3D Reconstruction Based on Dense Subpixel Disparity Map Estimation (Fan et al., 2018)]]

We used the following datasets to test and build our project:
1. [[http://www.cvlibs.net/datasets/kitti/][KITTI 2012 and 2015]]

** NOTE 
Much of this project was worked on through various branches and via Live Share sessions on VS Code.
Due to this, commit history is limited mostly to those who hosted the Live sessions.


** DESCRIPTION 
This goal of this project was to replicate, to the best of our ability, as many of the published papers
regarding the novel method of dense subpixel disparity map estimation for the purpose of road surface reconstruction.
The original researchers have published several papers, in 2013, 2017, and 2018
We extensively studied all 3 papers, and using information throughout all, were able to replicate the following:


*** WHAT WAS DONE
**** Paper 2013
- Fully completed replication of the published 2013 paper
- Replication of the custom stereo matching search range
- Full building of left and right dense disparity maps
- Full build of a left-right consistency checked dense disparity map

**** Paper 2017
- Initialized integral and integral squared images for quick sum 
- Initialized mean and sigma maps for memorization and quick lookups
- Wrote the framework for the left disparity map using integral images and mean/sigma maps. (Not functioning, strange output)

**** Paper 2018
- Found keypoints for matching, and perspective transform but didn't complete least squares fitting
- Read and evaluated paper, presented on it in class

* Installation
#+begin_src 
python3 -m pip install -r requirements.txt
#+end_src

* Datasets
We used the KITTI dataset provided from the link above.
There are 3 stereo image pairs provided from said dataset with this project which correspond to the images in the results of the 2013 paper.
000003_10.png, 000009_10.png, 000112_10.png

* Running the program 
We provide a demo method for you to run the program.

** Comprehensive Demo
The following will run a comprehensive demonstration of what we have completed, described above.
All output images will be produced, marked with <image_type>00000<image_number>.png

#+begin_src
python3 main.py --demo=True
#+end_src

** List of images that will be produced:
*** 2013 Paper
- left_disparity_map
- right_disparity_map
- result_disparity_map (left-right consistency checked dense disparity map)

*** 2017 Paper
- left_int_image, left_int_image_squared
- right_int_image, right_int_image_squared
- left_mu_map
- right_mu_map
- left_sigma_map
- right_sigma_map

If you want to run anything other than the demo, the following arguments exist and MUST have values.end_src
--left_img=[PATH_TO_LEFT_STEREO_IMAGE]
--right_img=[PATH_TO_RIGHT_STEREO_IMAGE]
--paper=[PAPER_IMPLEMENTATION_TO_RUN] 
--disp_thresh=[CONSISTENCY_CHECK_THROWOUT_THRESHOLD]

Acceptable values for paper include "2013" and "2017"
Acceptable values for disp_thresh should be between 5-10
